services:
  docker:
    image: docker:dind
    privileged: true
    ports:
      - "2375:2375"
    expose:
      - "2375"
    volumes:
      - dind-storage:/var/lib/docker
    environment:
      - DOCKER_TLS_CERTDIR=

  jenkins:
    image: jenkins-docker-enabled
    privileged: true
    user: root
    depends_on:
      - docker
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - DOCKER_HOST=tcp://docker:2375
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
  dind-storage:
